# Generated by Django 4.2.17 on 2025-04-22 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.CONFIG_CONFIG_MODEL),
        migrations.swappable_dependency(settings.CONFIG_TEMPLATE_MODEL),
        ('openwisp_users', '0020_populate_password_updated_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tunnel', max_length=128)),
                ('vpn_type', models.CharField(choices=[('ipsec', 'IPsec'), ('openvpn', 'OpenVPN'), ('vxlan', 'VXLAN')], max_length=20)),
                ('mode', models.CharField(choices=[('site_to_site', 'Site-to-Site'), ('hub_spoke', 'Hub & Spoke'), ('full_mesh', 'Full Mesh')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error')], default='pending', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_config_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_device_a', to=settings.CONFIG_CONFIG_MODEL)),
                ('device_b', models.ManyToManyField(blank=True, related_name='as_device_b', to=settings.CONFIG_CONFIG_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openwisp_users.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.CONFIG_TEMPLATE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TunnelStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('log', models.TextField()),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexapp_vpn.tunnel')),
            ],
        ),
        migrations.CreateModel(
            name='TunnelHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency_ms', models.FloatField()),
                ('jitter_ms', models.FloatField()),
                ('packet_loss_percent', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='nexapp_vpn.tunnel')),
            ],
        ),
        migrations.CreateModel(
            name='TunnelConfigHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_snapshot', models.TextField()),
                ('config_text', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openwisp_users.organizationuser')),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_history', to='nexapp_vpn.tunnel')),
            ],
        ),
        migrations.CreateModel(
            name='DevicePeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_device_name', models.CharField(max_length=128)),
                ('local_ip', models.GenericIPAddressField()),
                ('peer_device_name', models.CharField(max_length=128)),
                ('peer_ip', models.GenericIPAddressField()),
                ('link_subnet', models.CharField(max_length=64)),
                ('local_role', models.CharField(choices=[('hub', 'Hub'), ('spoke', 'Spoke')], max_length=16)),
                ('peer_role', models.CharField(choices=[('hub', 'Hub'), ('spoke', 'Spoke')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openwisp_users.organization')),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_peers', to='nexapp_vpn.tunnel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tunnel',
            constraint=models.UniqueConstraint(fields=('device_a', 'name'), name='unique_tunnel_per_device_a'),
        ),
        migrations.AlterUniqueTogether(
            name='devicepeer',
            unique_together={('tunnel', 'local_device_name', 'peer_device_name')},
        ),
    ]
